# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.chrome.options import Options
# use env for servers
# eg os.environ["SELENIUM"]

class Test():
  def setup_method(self, method):
      self.options = Options()
      self.options.add_argument("--headless")
      self.options.headless = True
      #self.driver = webdriver.Chrome()             #driver must be in PATH
      self.driver = webdriver.Remote("http://selenium:4444/wd/hub", DesiredCapabilities.CHROME)             #driver must be in PATH

      self.vars = {}

  def teardown_method(self, method):
      self.driver.quit()

  def test1(self):
      # TEST 1
      self.driver.get("http://front:4444/")
      print(self.driver.current_url)
      self.driver.set_window_size(1657, 933)
      self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
      self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
      self.driver.find_element(By.NAME, "firstName").click()
      self.driver.find_element(By.NAME, "firstName").send_keys("TESTUSER")
      self.driver.find_element(By.NAME, "lastName").send_keys("TESTUSER")
      self.driver.find_element(By.NAME, "address").send_keys("TEST_ADDR")
      self.driver.find_element(By.NAME, "city").send_keys("TEST_CITY")
      self.driver.find_element(By.NAME, "telephone").send_keys("123123123")
      self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
      self.driver.implicitly_wait(3)
      print(self.driver.current_url)

  def test2(self):
      # TEST 2
      # TEST 1
      self.driver.get("http://front:4444/")
      print(self.driver.current_url)
      self.driver.set_window_size(1657, 933)
      self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
      self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
      self.driver.find_element(By.NAME, "firstName").click()
      self.driver.find_element(By.NAME, "firstName").send_keys("TESTUSER")
      self.driver.find_element(By.NAME, "lastName").send_keys("TESTUSER")
      self.driver.find_element(By.NAME, "address").send_keys("TEST_ADDR")
      self.driver.find_element(By.NAME, "city").send_keys("TEST_CITY")
      self.driver.find_element(By.NAME, "telephone").send_keys("123123123")

      btn = self.driver.find_element(By.XPATH, "//button[contains(., 'Add Owner')]")
      self.driver.execute_script("arguments[0].click();", btn)
      #self.driver.find_element(By.CSS_SELECTOR, "button[type='submit']").click()
      #print(self.driver.find_element(By.CSS_SELECTOR, "button[type='submit']").text)

      print("Waiting for click")
      print(self.driver.current_url)
      self.driver.implicitly_wait(3)

      self.driver.save_screenshot('screenie.png')
      print(self.driver.current_url)
      #print(self.driver.page_source)
      self.driver.find_element(By.XPATH, "//a[contains(., 'Add New Pet')]").click()
      self.driver.execute_script("window.scrollTo(0,0)")
      self.driver.find_element(By.NAME, "name").click()
      self.driver.find_element(By.NAME, "name").send_keys("PETTEST")

      self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__input-container").click()
      self.driver.find_element(By.CSS_SELECTOR, ".form-control.react-datepicker-ignore-onclickoutside").click()
      self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__week:nth-child(2) > .react-datepicker__day:nth-child(4)").click()
      self.dropdown = self.driver.find_element(By.NAME, "typeId")
      self.dropdown.find_element(By.XPATH, "//option[. = 'cat']").click()
      self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
      self.driver.find_element(By.CSS_SELECTOR, ".btn").click()


  def test3(self):
      # TEST 3
      # TEST 2
      # TEST 1
      self.driver.get("http://front:4444/")
      self.driver.set_window_size(1657, 933)
      self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
      self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
      self.driver.find_element(By.NAME, "firstName").click()
      self.driver.find_element(By.NAME, "firstName").send_keys("TESTUSER")
      self.driver.find_element(By.NAME, "lastName").send_keys("TESTUSER")
      self.driver.find_element(By.NAME, "address").send_keys("TEST_ADDR")
      self.driver.find_element(By.NAME, "city").send_keys("TEST_CITY")
      self.driver.find_element(By.NAME, "telephone").send_keys("123123123")
      self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
      self.driver.implicitly_wait(3)
      self.driver.find_element(By.XPATH, "//a[contains(., 'Add New Pet')]").click()
      self.driver.execute_script("window.scrollTo(0,0)")
      self.driver.find_element(By.NAME, "name").click()
      self.driver.find_element(By.NAME, "name").send_keys("PETTEST")

      self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__input-container").click()
      self.driver.find_element(By.CSS_SELECTOR, ".form-control.react-datepicker-ignore-onclickoutside").click()
      self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__week:nth-child(2) > .react-datepicker__day:nth-child(4)").click()
      self.dropdown = self.driver.find_element(By.NAME, "typeId")
      self.dropdown.find_element(By.XPATH, "//option[. = 'cat']").click()
      self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
      self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

      self.driver.find_element(By.LINK_TEXT, "Add Visit").click()
      self.driver.execute_script("window.scrollTo(0,0)")
      self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__input-container").click()
      self.driver.find_element(By.CSS_SELECTOR, ".form-control.react-datepicker-ignore-onclickoutside").click()
      self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__week:nth-child(2) > .react-datepicker__day:nth-child(4)").click()
      self.driver.find_element(By.NAME, "description").click()
      self.driver.find_element(By.NAME, "description").send_keys("qweqwe")
      self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

#element = driver.find_element(By.CSS_SELECTOR, ".btn")
#actions = ActionChains(driver)
#actions.move_to_element(element).perform()
#driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) span:nth-child(2)").click()

