# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome("/tmp/chromedriver")
driver.get("http://localhost:4444/")
driver.set_window_size(1475, 1053)

# TEST 1
driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
driver.find_element(By.LINK_TEXT, "Add Owner").click()
driver.find_element(By.NAME, "firstName").click()
driver.find_element(By.NAME, "firstName").send_keys("TESTUSER")
driver.find_element(By.NAME, "lastName").send_keys("TESTUSER")
driver.find_element(By.NAME, "address").send_keys("TEST_ADDR")
driver.find_element(By.NAME, "city").send_keys("TEST_CITY")
driver.find_element(By.NAME, "telephone").send_keys("123123123")
driver.find_element(By.CSS_SELECTOR, ".btn").click()

driver.implicitly_wait(3)
# TEST 2
driver.find_element(By.CSS_SELECTOR, "a[href*=new]").click()
driver.execute_script("window.scrollTo(0,0)")
driver.find_element(By.NAME, "name").click()
driver.find_element(By.NAME, "name").send_keys("PETTEST")

driver.find_element(By.CSS_SELECTOR, ".react-datepicker__input-container").click()
driver.find_element(By.CSS_SELECTOR, ".form-control.react-datepicker-ignore-onclickoutside").click()
driver.find_element(By.CSS_SELECTOR, ".react-datepicker__week:nth-child(2) > .react-datepicker__day:nth-child(4)").click()

dropdown = driver.find_element(By.NAME, "typeId")
dropdown.find_element(By.XPATH, "//option[. = 'cat']").click()
driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
driver.find_element(By.CSS_SELECTOR, ".btn").click()


# TEST 3
driver.find_element(By.LINK_TEXT, "Add Visit").click()
driver.execute_script("window.scrollTo(0,0)")

driver.find_element(By.CSS_SELECTOR, ".react-datepicker__input-container").click()
driver.find_element(By.CSS_SELECTOR, ".form-control.react-datepicker-ignore-onclickoutside").click()
driver.find_element(By.CSS_SELECTOR, ".react-datepicker__week:nth-child(2) > .react-datepicker__day:nth-child(4)").click()

driver.find_element(By.NAME, "description").click()
driver.find_element(By.NAME, "description").send_keys("qweqwe")
driver.find_element(By.CSS_SELECTOR, ".btn").click()


#element = driver.find_element(By.CSS_SELECTOR, ".btn")
#actions = ActionChains(driver)
#actions.move_to_element(element).perform()
#driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) span:nth-child(2)").click()

driver.quit()
